### ISSUE TITLE
feat: add typings for @wdio/sync

### ISSUE THREAD

**Issue by ennjin** [ennjin/wdio-visual-regression#11]
There was #8 PR to solve this but implementation is incorrect. The actual problem is conflict typings between `WebdriverIO` and `WebdriverIOAsync` namespace because the first one extended from second one. Need another solution.

@dpoetzsch You are welcome to try fix it :smiley:

**Comment by dpoetzsch** [comment]
Hi,

for me using `@wdio/sync` they work fine. Probably the error occurs when using the async mode?

I did not find the code where one namespace extends the other, it does not seem to be in the typings of `@wdio/sync` (https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-sync/webdriverio-core.d.ts and https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-sync/webdriverio.d.ts).

As I need to include the typings file manually in my tsconfig anyway, one solution could be to provide two different files, one for sync and one for async mode?

**Comment by dpoetzsch** [comment]
Ah, I think I found the problematic line: https://github.com/webdriverio/webdriverio/blob/edf6d1fb7ee7e401d12f8054d57e2c1685311479/packages/webdriverio/webdriverio.d.ts#L113

I will think of a possible solution.
